version: '3.8'

services:
  app:
    build: .
    container_name: telegram-bot-python
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ 'gpu' ]
    volumes:
      - .:/app
    ports:
      - "5000:5000"
